- name: Cleanup before destroy
  hosts: all
  gather_facts: yes
  tasks:
    - name: Ensure /tmp exists
      stat:
        path: /tmp
      register: tmp_dir

    - name: Remove temp file if /tmp exists
      file:
        path: /tmp/test-cleanup.txt
        state: absent
      when: tmp_dir.stat.exists
