---
- name: Cleanup before destroy
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping to check connectivity
      ping:
      register: ping_result
      ignore_errors: true

    - name: Skip cleanup if unreachable
      meta: end_play
      when: ping_result is failed

    - name: Ensure /tmp exists
      stat:
        path: /tmp
      register: tmp_dir

    - name: Remove temp file if /tmp exists
      file:
        path: /tmp/test-cleanup.txt
        state: absent
      when: tmp_dir.stat.exists
