- name: Cleanup before destroy
  hosts: all
  gather_facts: no

  tasks:
    - name: Check container availability (ping via localhost)
      delegate_to: localhost
      command: docker inspect -f '{{ .State.Running }}' ansible-role-test
      register: container_status
      failed_when: false
      changed_when: false
      ignore_errors: true

    - name: Skip cleanup if container is not running
      meta: end_play
      when: container_status.rc != 0 or "'true'" not in container_status.stdout

    - name: Ensure /tmp exists
      stat:
        path: /tmp
      register: tmp_dir

    - name: Remove temp file if /tmp exists
      file:
        path: /tmp/test-cleanup.txt
        state: absent
      when: tmp_dir.stat.exists
