dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ansible-role-test
    image: geerlingguy/docker-centos7-ansible
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      
  - name: ansible-role-test-debian
    image: geerlingguy/docker-debian10-ansible
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro      
      
provisioner:
  name: ansible

verifier:
  name: testinfra

scenario:
  name: default
