dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ansible-role-test
    image: geerlingguy/docker-debian9-ansible
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible

verifier:
  name: testinfra

scenario:
  name: default
